# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: main-ingress
#   annotations:
#     # Traefik specific annotations
#     traefik.ingress.kubernetes.io/router.entrypoints: web
# spec:
#   ingressClassName: traefik
#   rules:
#   # Rule for app1.com -> nginx service
#   - host: app1.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: nginx-service
#             port:
#               number: 80
#   # Rule for app2.com -> apache service (3 replicas)
#   - host: app2.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: apache-service
#             port:
#               number: 80
#   # Default rule (catch-all) for any other host -> default app
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: default-app-service
#             port:
#               number: 80
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
spec:
  rules:
  # Rule for app1.com -> nginx service
  - host: app1.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  # Rule for app2.com -> apache service (3 replicas)
  - host: app2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache-service
            port:
              number: 80
  # Default rule (catch-all) for any other host -> default app
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: default-app-service
            port:
              number: 80