$script = <<-'SCRIPT'
curl -sfL https://get.k3s.io | sh -
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.box = "generic/centos7"

  #Server
  config.vm.define "server" do |server|
    server.vm.hostname = "nponchonS"
    server.vm.network :private_network, ip: "192.168.56.110"
    config.vm.provision "shell",
        inline: $script
  end

  #ServiceWorker
  config.vm.define "serverWorker" do |serverWorker|
    serverWorker.vm.hostname = "nponchonSW"
    serverWorker.vm.network :private_network, ip: "192.168.56.111"
  end

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "512"
     vb.cpus = 1
  end
end
