global:
  time_zone: "Europe/Madrid"
  hosts:
    domain: localhost
    https: false
  ingress:
    enabled: false
  resources:
    limits:
      memory: 2Gi
      cpu: 1000m
    requests:
      memory: 512Mi
      cpu: 200m

gitlab:
  webservice:
    livenessProbe:
      initialDelaySeconds: 180
      periodSeconds: 60
      timeoutSeconds: 60
      failureThreshold: 10
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 30
      failureThreshold: 10

    workerProcesses: 1
    puma:
      workerMaxMemory: 400
    minReplicas: 1
    maxReplicas: 1
    ingress:
      enabled: false

    resources:
      limits:
        memory: 1.5Gi
        cpu: 500m
      requests:
        memory: 1Gi
        cpu: 200m

  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    resources:
      limits:
        memory: 256Mi
        cpu: 200m
      requests:
        memory: 128Mi
        cpu: 50m
    service:
      type: NodePort
      nodePort: 2222

  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    pods:
      - name: all-in-1
        concurrency: 3
        resources:
          requests:
            memory: 300Mi
          limits:
            memory: 600Mi

  gitaly:
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 100m

gitlab-rails:
  extraEnv:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.localhost'
      gitlab_rails['trusted_proxies'] = ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']
      nginx['listen_port'] = 8080
      nginx['listen_https'] = false
      nginx['proxy_set_headers'] = {
        'Host' => '$http_host',
        'X-Real-IP' => '$remote_addr',
        'X-Forwarded-For' => '$proxy_add_x_forwarded_for',
        'X-Forwarded-Proto' => 'http'
      }

certmanager-issuer:
  email: nponchon@student.42barcelona.com

postgresql:
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 100m

redis:
  resources:
    limits:
      memory: 256Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 50m

gitlab-runner:
  install: false

registry:
  enabled: false

prometheus:
  install: false

grafana:
  enabled: false

nginx-ingress:
  enabled: false

gitlab-kas:
  enabled: false

gitlab-pages:
  enabled: false

gitlab-exporter:
  enabled: false
