global:
  time_zone: "Europe/Madrid"
  hosts:
    domain: localhost
    https: false
  ingress:
    enabled: false

gitlab:
  webservice:
    ingress:
      enabled: false

gitlab-rails:
  extraEnv:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.localhost'
      gitlab_rails['trusted_proxies'] = ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']
      nginx['listen_port'] = 8080
      nginx['listen_https'] = false
      nginx['proxy_set_headers'] = {
        'Host' => '$http_host',
        'X-Real-IP' => '$remote_addr',
        'X-Forwarded-For' => '$proxy_add_x_forwarded_for',
        'X-Forwarded-Proto' => 'http'
      }

certmanager-issuer:
  email: nponchon@student.42barcelona.com

# Disable components we don't need
gitlab-runner:
  install: false

registry:
  enabled: false

prometheus:
  install: false

grafana:
  enabled: false